server:
  port: 9000

temporal:
  namespace: storefront

restclient:
  order:
    name: OrderRestClient
    url: http://localhost:9001/order
  inventory:
    name: InventoryRestClient
    url: http://localhost:9002/items
  payment:
    name: PaymentRestClient
    url: http://localhost:9003/payment
  notification:
    name: NotificationRestClient
    url: http://localhost:9004/notify
